version: '2'
services:
  mysql:
   image: mysql:latest
   environment:
     MYSQL_ROOT_PASSWORD: password
   ports:
     - 3306
   volumes:
     - ./dbdump:/docker-entrypoint-initdb.d
  registration:
    ports:
     - "1111"
    image: emcdevops/registration:$VERSION
  accounts:
    ports:
     - "2222"
    environment:
     - SPRING_PROFILES_ACTIVE=Test
    image: emcdevops/accounts:$VERSION
    depends_on:
     - registration
     - mysql
    links:
     - mysql
  web:
    ports:
     - "3333"
    image: emcdevops/web:$VERSION
    depends_on:
     - registration
