apiVersion: v1
kind: ReplicationController
metadata:
  name: accounts-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
      - name: accounts
        image: emcdevops/accounts:latest
        ports:
        - containerPort: 2222
        imagePullPolicy: Always
